# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: particle.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'particle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eparticle.proto\"\x1c\n\x0bStepRequest\x12\r\n\x05steps\x18\x01 \x01(\x05\"I\n\x0cStepResponse\x12\x12\n\nreplica_id\x18\x01 \x01(\t\x12\x12\n\nlatency_ms\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32\x32\n\x0bParticleSim\x12#\n\x04Step\x12\x0c.StepRequest\x1a\r.StepResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'particle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STEPREQUEST']._serialized_start=18
  _globals['_STEPREQUEST']._serialized_end=46
  _globals['_STEPRESPONSE']._serialized_start=48
  _globals['_STEPRESPONSE']._serialized_end=121
  _globals['_PARTICLESIM']._serialized_start=123
  _globals['_PARTICLESIM']._serialized_end=173
# @@protoc_insertion_point(module_scope)
